### ISSUE TITLE
plugin doesn't work because postcss.plugin is deprecated

### ISSUE THREAD

**Issue by felixsanz** [EdMSL/postcss-color-converter#13]
```
postcss-color-converter: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.6, but postcss-color-converter uses 8.4.12. Perhaps this is the source of the error below.
error: Uncaught (in promise) Error: 238 is not a PostCSS plugin
```

Any plan to update it?

**Comment by EdMSL** [comment]
@felixsanz I will do it on the weekend.

**Comment by EdMSL** [comment]
Updated to 1.1.0
@felixsanz Please, test new version. If everything will good I will close the issue.

**Comment by felixsanz** [comment]
`error: Uncaught (in promise) Error: 258 is not a PostCSS plugin`

I think postcss-values-parser is not 8.x compatible

**Comment by EdMSL** [comment]
@felixsanz  How do you use this plugin?
I use it from `postcss-cli` and everithing works fine.
I created the test project, you can clone it and test. [test-app](https://github.com/EdMSL/test-app)

**Comment by felixsanz** [comment]
i import `colorConverter` and then:
```js
  const plugins = postcss([
    // other plugins... and no problem with them,
    colorConverter({ outputColorFormat: 'hex' }),
  ])
  return plugins
    .process(css, { from: undefined })
    .then((result) => result.css)
```

**Comment by EdMSL** [comment]
I can't reproduce the problem. I created a pure Node project, installed the packages and created a script with your code: 
```javascript
var fs = require("fs")
var postcss = require("postcss")
var colorConverter = require("postcss-color-converter")

// css to be processed
var css = fs.readFileSync("input.css", "utf8")

const plugins = postcss([
    colorConverter({ outputColorFormat: 'hex' }),
  ])

plugins
  .process(css, { from: undefined })
  .then((result) => console.log(result.css))
```
added a css file:
```css
a {
    color: red;
}
```
and got the output to the console:
```javascript
a {
    color: #ff0000;
}
```

**Comment by felixsanz** [comment]
i'm using deno and importing everything via esm.sh, maybe the problem is that :/

**Comment by EdMSL** [comment]
I don't know. I have not tested the plugin with Deno and have never used it.

**Comment by felixsanz** [comment]
Well, since it works with node and npm, the upgrade is complete! thanks
