### ISSUE TITLE
Converts values containing calc or variables

### ISSUE THREAD

**Issue by Tofandel** [EdMSL/postcss-color-converter#2]
Given the property
`background: hsl(calc(10 + 20), 10%, 10%)`
or 
`background: hsl(var(--hue), 10%, 10%)`

The plugin will try to convert it but will fail and replace it with `#000000` which is not correct, it should leave them as is

**Comment by EdMSL** [comment]
Thanks for the problem found. I will fix this soon.

**Comment by EdMSL** [comment]
Fixed in 1.0.1.
